version: '3.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es01
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      discovery.type: zen
      discovery.seed_hosts: es02,es03
      cluster.initial_master_nodes: es01,es02,es03
      network.host: 0.0.0.0
      xpack.security.enabled: "false"
      xpack.watcher.enabled: "false"
      xpack.monitoring.enabled: "true"
      xpack.ml.enabled: "false"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - elasticsearch
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es02
    environment:
      node.name: es02
      cluster.name: es-docker-cluster
      discovery.type: zen
      discovery.seed_hosts: es01,es03
      cluster.initial_master_nodes: es01,es02,es03
      network.host: 0.0.0.0
      xpack.security.enabled: "false"
      xpack.watcher.enabled: "false"
      xpack.monitoring.enabled: "true"
      xpack.ml.enabled: "false"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - elasticsearch
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es03
    environment:
      node.name: es03
      cluster.name: es-docker-cluster
      discovery.type: zen
      discovery.seed_hosts: es01,es02
      cluster.initial_master_nodes: es01,es02,es03
      network.host: 0.0.0.0
      xpack.security.enabled: "false"
      xpack.watcher.enabled: "false"
      xpack.monitoring.enabled: "true"
      xpack.ml.enabled: "false"
      ES_JAVA_OPTS: -Xms256m -Xmx256m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
    networks:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    container_name: log01
    environment:
      http.host: "0.0.0.0"
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "true"
      xpack.monitoring.elasticsearch.hosts: "http://es01:9200"
    ports:
      - "5000:5000"
      - "9600:9600"
      - "8080:8080"
      - "5044:5044"
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elasticsearch
    depends_on:
      - es01
      - es02
      - es03

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kib01
    environment:
      server.name: kib01
      server.host: "0"
      xpack.security.enabled: "false"
      xpack.monitoring.ui.container.elasticsearch.enabled: "true"
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    links:
      - es01
      - es02
      - es03
    volumes:
      - data05:/usr/share/elasticsearch/data
    ports:
      - "5601:5601"
    networks:
      - elasticsearch
    depends_on:
      - es01
      - es02
      - es03

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  data05:
    driver: local

networks:
  elasticsearch:
    driver: bridge